name: Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.14.0
      - name: build docker image
        run: docker build . -t kuli:staging
      - name: push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-central-1
          image: kuli-staging
          local-image: kuli:staging
      - name: Restart the ECS tasks
        run: |
          aws ecs update-service --service kuli-staging --cluster kuli-staging --force-new-deployment --region  us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
